# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8c545b9946ed9f544fca84ce1e5adfe3bae835a03a8568eb1608e7fc0fedb9594e5cb69fa2826ca62422405e789ad6da578b139a7f9553a00e539be77f0e99eb

test:
  secret_key_base: 6214aa40e59e29123df68b5d6755cb5ad1f2404ed776ce22ed20f844df35e84dd0fb53c16c7819de3fa69e11b6a22e18b852c189158180b8443dfddbb8509a1d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
